<a href="https://colab.research.google.com/github/KouFkaS7/PracticeWithPandas/blob/main/CleaningData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import re
import string

In [2]:
data = pd.read_excel(r'/content/TELIKO_SERRES.xlsx')

In [3]:
df = pd.DataFrame(data)
df.head()

,type,code_system,price,area,location,street,bedrooms,floor,kitchen,bath,wc,loft,heating,energy_class,y_build,y_renovation,code_home
0,"Μονοκατοικία, 90τ.μ.",12639939,€155.000,90τ.μ.,"Καλύβια, Σέρρες (Ν. Σέρρες)","Βύρωνος 13 Σέρρες, Σέρρες, 62125",2\n \n υ/δ,Ημιόροφος,1.0,1.0,1.0,1.0,Αυτόνομη\n (Πετρέλαιο),Γ\n 100%-141%,1975,2010.0,NaN
1,"Μονοκατοικία, 232τ.μ.",15839907,€235.000\n €245.000 (Συζητήσ...,232τ.μ.,"Κάτω Μετόχι, Σέρρες (Ν. Σέρρες)",NaN,3\n \n υ/δ,Ισόγειο,2.0,2.0,2.0,2.0,Αυτόνομη\n (Πετρέλαιο),Δ\n 141%-182%,1998,NaN,10-8106
2,"Διαμέρισμα, 110τ.μ.",16596218,€95.000,110τ.μ.,"Άνω Καμενίκια, Σέρρες (Ν. Σέρρες)",NaN,NaN,1ος,NaN,NaN,NaN,NaN,NaN,Εξαιρείται από την υποχρεωτική έκδοση ΠΕΑ,NaN,NaN,NaN
3,"Διαμέρισμα, 110τ.μ.",16848288,€165.000,110τ.μ.,"Κέντρο, Σέρρες (Ν. Σέρρες)","Βενιζέλου Ελευθερίου, 31 621 23 Σέρρες",3\n \n υ/δ,2ος,1.0,1.0,NaN,1.0,Αυτόνομη\n (Φυσικό αέριο),Β+\n 50%-75%,1985,NaN,NaN
4,"Διαμέρισμα, 93τ.μ.",16289562,€85.000,93τ.μ.,"Κέντρο, Σέρρες (Ν. Σέρρες)",Δυτικής Θράκης 621 23 Σέρρες,2\n \n υ/δ,4ος,1.0,1.0,NaN,1.0,Κεντρική\n (Τηλεθέρμανση),Το ΠΕΑ είναι υπό έκδοση,1982,NaN,NaN

In [4]:
df['type'] = df['type'].str.split(',').str[0]

In [5]:
df['price'] = df['price'].str.lstrip('€')

In [6]:
df['area'] = df['area'].str.extract(r'(\d+)')

In [7]:
df['price'] = df['price'].str.replace('.','',regex=False)

In [8]:
df['location'] = df['location'].str.split(',').str[0]

In [9]:
df['location'].unique()

array(['Καλύβια', 'Κάτω Μετόχι', 'Άνω Καμενίκια', 'Κέντρο', 'Καλλιθέα',
       'Σέρρες (Ν. Σέρρες)', 'Πυροβολικά', 'Καλκάνη', 'Κάτω Καμενίκια',
       'Άγιος Ιωάννης', 'Κιουπλιά', 'Οινούσσα', 'Επτάμυλοι', 'Ξηρότοπος',
       'Χρυσοπηγή', 'Χιονοχώρι', 'Ελαιώνας',
       'Μονή Τιμίου Προδρόμου Σερρών', 'Μαρμαράς'], dtype=object)

In [10]:
df.head(5)

,type,code_system,price,area,location,street,bedrooms,floor,kitchen,bath,wc,loft,heating,energy_class,y_build,y_renovation,code_home
0,Μονοκατοικία,12639939,155000,90,Καλύβια,"Βύρωνος 13 Σέρρες, Σέρρες, 62125",2\n \n υ/δ,Ημιόροφος,1.0,1.0,1.0,1.0,Αυτόνομη\n (Πετρέλαιο),Γ\n 100%-141%,1975,2010.0,NaN
1,Μονοκατοικία,15839907,235000\n €245000 (Συζητήσιμη),232,Κάτω Μετόχι,NaN,3\n \n υ/δ,Ισόγειο,2.0,2.0,2.0,2.0,Αυτόνομη\n (Πετρέλαιο),Δ\n 141%-182%,1998,NaN,10-8106
2,Διαμέρισμα,16596218,95000,110,Άνω Καμενίκια,NaN,NaN,1ος,NaN,NaN,NaN,NaN,NaN,Εξαιρείται από την υποχρεωτική έκδοση ΠΕΑ,NaN,NaN,NaN
3,Διαμέρισμα,16848288,165000,110,Κέντρο,"Βενιζέλου Ελευθερίου, 31 621 23 Σέρρες",3\n \n υ/δ,2ος,1.0,1.0,NaN,1.0,Αυτόνομη\n (Φυσικό αέριο),Β+\n 50%-75%,1985,NaN,NaN
4,Διαμέρισμα,16289562,85000,93,Κέντρο,Δυτικής Θράκης 621 23 Σέρρες,2\n \n υ/δ,4ος,1.0,1.0,NaN,1.0,Κεντρική\n (Τηλεθέρμανση),Το ΠΕΑ είναι υπό έκδοση,1982,NaN,NaN

In [11]:
df['bedrooms'] = df['bedrooms'].str.extract(r'(\d+)')
df

,type,code_system,price,area,location,street,bedrooms,floor,kitchen,bath,wc,loft,heating,energy_class,y_build,y_renovation,code_home
0,Μονοκατοικία,12639939,155000,90,Καλύβια,"Βύρωνος 13 Σέρρες, Σέρρες, 62125",2,Ημιόροφος,1.0,1.0,1.0,1.0,Αυτόνομη\n (Πετρέλαιο),Γ\n 100%-141%,1975,2010.0,NaN
1,Μονοκατοικία,15839907,235000\n €245000 (Συζητήσιμη),232,Κάτω Μετόχι,NaN,3,Ισόγειο,2.0,2.0,2.0,2.0,Αυτόνομη\n (Πετρέλαιο),Δ\n 141%-182%,1998,NaN,10-8106
2,Διαμέρισμα,16596218,95000,110,Άνω Καμενίκια,NaN,NaN,1ος,NaN,NaN,NaN,NaN,NaN,Εξαιρείται από την υποχρεωτική έκδοση ΠΕΑ,NaN,NaN,NaN
3,Διαμέρισμα,16848288,165000,110,Κέντρο,"Βενιζέλου Ελευθερίου, 31 621 23 Σέρρες",3,2ος,1.0,1.0,NaN,1.0,Αυτόνομη\n (Φυσικό αέριο),Β+\n 50%-75%,1985,NaN,NaN
4,Διαμέρισμα,16289562,85000,93,Κέντρο,Δυτικής Θράκης 621 23 Σέρρες,2,4ος,1.0,1.0,NaN,1.0,Κεντρική\n (Τηλεθέρμανση),Το ΠΕΑ είναι υπό έκδοση,1982,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
505,Studio / Γκαρσονιέρα,16238056,39000,35,Κέντρο,"Φιλίππου 4, 621 24 Σέρρες",NaN,Ισόγειο,NaN,NaN,NaN,NaN,NaN,Ε\n 182%-227%,NaN,NaN,NaN
506,Μονοκατοικία,14211027,73000,93,Κέντρο,"Κιθαιρώνος, 4",NaN,Ισόγειο,NaN,NaN,NaN,NaN,NaN,Η\n >273%,1968,NaN,NaN
507,Μονοκατοικία,16558726,400000,165,Καλλιθέα,"Δραγούμη Ίωνος, 19 621 22 Σέρρες",NaN,NaN,NaN,NaN,NaN,NaN,Αυτόνομη\n (Πετρέλαιο),Εξαιρείται από την υποχρεωτική έκδοση ΠΕΑ,1938,NaN,NaN
508,Μονοκατοικία,15265799,82000,108,Καλύβια,"Πύρρου, 2",NaN,Ισόγειο,NaN,NaN,NaN,NaN,Χωρίς θέρμανση,Η\n >273%,1950,NaN,NaN
509,Μονοκατοικία,13864460,63000,74,Καλύβια,"Σαλαμίνος, 18",1,Ισόγειο,1.0,1.0,1.0,1.0,NaN,Α+\n <33%,NaN,NaN,NaN

In [12]:
df['bedrooms'].isnull().sum()

53

In [13]:
df['floor']

0      Ημιόροφος
1        Ισόγειο
2            1ος
3            2ος
4            4ος
         ...
505      Ισόγειο
506      Ισόγειο
507          NaN
508      Ισόγειο
509      Ισόγειο
Name: floor, Length: 510, dtype: object

In [14]:
df['floor'] = df['floor'].replace({'Ισόγειο': 0, 'Ημιόροφος': 0.5})
df['floor'] = df['floor'].replace({'1ος': 1, '2ος': 2, '3ος': 3, '4ος': 4})
df

,type,code_system,price,area,location,street,bedrooms,floor,kitchen,bath,wc,loft,heating,energy_class,y_build,y_renovation,code_home
0,Μονοκατοικία,12639939,155000,90,Καλύβια,"Βύρωνος 13 Σέρρες, Σέρρες, 62125",2,0.5,1.0,1.0,1.0,1.0,Αυτόνομη\n (Πετρέλαιο),Γ\n 100%-141%,1975,2010.0,NaN
1,Μονοκατοικία,15839907,235000\n €245000 (Συζητήσιμη),232,Κάτω Μετόχι,NaN,3,0,2.0,2.0,2.0,2.0,Αυτόνομη\n (Πετρέλαιο),Δ\n 141%-182%,1998,NaN,10-8106
2,Διαμέρισμα,16596218,95000,110,Άνω Καμενίκια,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,Εξαιρείται από την υποχρεωτική έκδοση ΠΕΑ,NaN,NaN,NaN
3,Διαμέρισμα,16848288,165000,110,Κέντρο,"Βενιζέλου Ελευθερίου, 31 621 23 Σέρρες",3,2,1.0,1.0,NaN,1.0,Αυτόνομη\n (Φυσικό αέριο),Β+\n 50%-75%,1985,NaN,NaN
4,Διαμέρισμα,16289562,85000,93,Κέντρο,Δυτικής Θράκης 621 23 Σέρρες,2,4,1.0,1.0,NaN,1.0,Κεντρική\n (Τηλεθέρμανση),Το ΠΕΑ είναι υπό έκδοση,1982,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
505,Studio / Γκαρσονιέρα,16238056,39000,35,Κέντρο,"Φιλίππου 4, 621 24 Σέρρες",NaN,0,NaN,NaN,NaN,NaN,NaN,Ε\n 182%-227%,NaN,NaN,NaN
506,Μονοκατοικία,14211027,73000,93,Κέντρο,"Κιθαιρώνος, 4",NaN,0,NaN,NaN,NaN,NaN,NaN,Η\n >273%,1968,NaN,NaN
507,Μονοκατοικία,16558726,400000,165,Καλλιθέα,"Δραγούμη Ίωνος, 19 621 22 Σέρρες",NaN,NaN,NaN,NaN,NaN,NaN,Αυτόνομη\n (Πετρέλαιο),Εξαιρείται από την υποχρεωτική έκδοση ΠΕΑ,1938,NaN,NaN
508,Μονοκατοικία,15265799,82000,108,Καλύβια,"Πύρρου, 2",NaN,0,NaN,NaN,NaN,NaN,Χωρίς θέρμανση,Η\n >273%,1950,NaN,NaN
509,Μονοκατοικία,13864460,63000,74,Καλύβια,"Σαλαμίνος, 18",1,0,1.0,1.0,1.0,1.0,NaN,Α+\n <33%,NaN,NaN,NaN

In [15]:
df['heating'] = df['heating'].apply(lambda x: x.split('(')[-1].split(')')[0] if isinstance(x, str) else x)

In [16]:
df['energy_class'] = df['energy_class'].replace({'Εξαιρείται από την υποχρεωτική έκδοση ΠΕΑ':np.NaN,'Το ΠΕΑ είναι υπό έκδοση':np.NaN})

In [17]:
df['energy_class'] = df['energy_class'].str[0]

In [18]:
df

,type,code_system,price,area,location,street,bedrooms,floor,kitchen,bath,wc,loft,heating,energy_class,y_build,y_renovation,code_home
0,Μονοκατοικία,12639939,155000,90,Καλύβια,"Βύρωνος 13 Σέρρες, Σέρρες, 62125",2,0.5,1.0,1.0,1.0,1.0,Πετρέλαιο,Γ,1975,2010.0,NaN
1,Μονοκατοικία,15839907,235000\n €245000 (Συζητήσιμη),232,Κάτω Μετόχι,NaN,3,0,2.0,2.0,2.0,2.0,Πετρέλαιο,Δ,1998,NaN,10-8106
2,Διαμέρισμα,16596218,95000,110,Άνω Καμενίκια,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Διαμέρισμα,16848288,165000,110,Κέντρο,"Βενιζέλου Ελευθερίου, 31 621 23 Σέρρες",3,2,1.0,1.0,NaN,1.0,Φυσικό αέριο,Β,1985,NaN,NaN
4,Διαμέρισμα,16289562,85000,93,Κέντρο,Δυτικής Θράκης 621 23 Σέρρες,2,4,1.0,1.0,NaN,1.0,Τηλεθέρμανση,NaN,1982,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
505,Studio / Γκαρσονιέρα,16238056,39000,35,Κέντρο,"Φιλίππου 4, 621 24 Σέρρες",NaN,0,NaN,NaN,NaN,NaN,NaN,Ε,NaN,NaN,NaN
506,Μονοκατοικία,14211027,73000,93,Κέντρο,"Κιθαιρώνος, 4",NaN,0,NaN,NaN,NaN,NaN,NaN,Η,1968,NaN,NaN
507,Μονοκατοικία,16558726,400000,165,Καλλιθέα,"Δραγούμη Ίωνος, 19 621 22 Σέρρες",NaN,NaN,NaN,NaN,NaN,NaN,Πετρέλαιο,NaN,1938,NaN,NaN
508,Μονοκατοικία,15265799,82000,108,Καλύβια,"Πύρρου, 2",NaN,0,NaN,NaN,NaN,NaN,Χωρίς θέρμανση,Η,1950,NaN,NaN
509,Μονοκατοικία,13864460,63000,74,Καλύβια,"Σαλαμίνος, 18",1,0,1.0,1.0,1.0,1.0,NaN,Α,NaN,NaN,NaN